version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/crypto-monitor
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
